apiVersion: v1
kind: ServiceAccount
metadata:
  name: clientfeaturediscovery-sa
  namespace: akash-services

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clientfeaturediscovery-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clientfeaturediscovery-binding
subjects:
- kind: ServiceAccount
  name: clientfeaturediscovery-sa
  namespace: akash-services
roleRef:
  kind: ClusterRole
  name: clientfeaturediscovery-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientfeaturediscovery
  namespace: akash-services
  labels:
    app: clientfeaturediscovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientfeaturediscovery
  template:
    metadata:
      labels:
        app: clientfeaturediscovery
    spec:
      serviceAccountName: clientfeaturediscovery-sa
      containers:
      - name: clientfeaturediscovery
        image: scarruthers/clientfeaturediscovery:v24
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
