// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/inventory/v1/storage.proto

package v1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StorageInfo struct {
	Vendor   string `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor" yaml:"vendor"`
	Class    string `protobuf:"bytes,2,opt,name=class,proto3" json:"class" yaml:"class"`
	Capacity string `protobuf:"bytes,3,opt,name=capacity,proto3" json:"capacity" yaml:"capacity"`
	IO       string `protobuf:"bytes,4,opt,name=IO,proto3" json:"io" yaml:"io"`
}

func (m *StorageInfo) Reset()         { *m = StorageInfo{} }
func (m *StorageInfo) String() string { return proto.CompactTextString(m) }
func (*StorageInfo) ProtoMessage()    {}
func (*StorageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ef685b221b1af7, []int{0}
}
func (m *StorageInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StorageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StorageInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StorageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageInfo.Merge(m, src)
}
func (m *StorageInfo) XXX_Size() int {
	return m.Size()
}
func (m *StorageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StorageInfo proto.InternalMessageInfo

func (m *StorageInfo) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *StorageInfo) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *StorageInfo) GetCapacity() string {
	if m != nil {
		return m.Capacity
	}
	return ""
}

func (m *StorageInfo) GetIO() string {
	if m != nil {
		return m.IO
	}
	return ""
}

type Storage struct {
	Quantity      *ResourcePair      `protobuf:"bytes,1,opt,name=quantity,proto3" json:"quantity" yaml:"quantity"`
	Info          *StorageInfo       `protobuf:"bytes,2,opt,name=info,proto3" json:"info" yaml:"info"`
	QuantityLocal *ResourcePairLocal `protobuf:"bytes,3,opt,name=quantitylocal,proto3" json:"quantitylocal" yaml:"quantitylocal"`
}

func (m *Storage) Reset()         { *m = Storage{} }
func (m *Storage) String() string { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()    {}
func (*Storage) Descriptor() ([]byte, []int) {
	return fileDescriptor_98ef685b221b1af7, []int{1}
}
func (m *Storage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Storage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Storage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Storage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storage.Merge(m, src)
}
func (m *Storage) XXX_Size() int {
	return m.Size()
}
func (m *Storage) XXX_DiscardUnknown() {
	xxx_messageInfo_Storage.DiscardUnknown(m)
}

var xxx_messageInfo_Storage proto.InternalMessageInfo

func (m *Storage) GetQuantity() *ResourcePair {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *Storage) GetInfo() *StorageInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Storage) GetQuantityLocal() *ResourcePairLocal {
	if m != nil {
		return m.QuantityLocal
	}
	return nil
}

func init() {
	proto.RegisterType((*StorageInfo)(nil), "akash.inventory.v1.StorageInfo")
	proto.RegisterType((*Storage)(nil), "akash.inventory.v1.Storage")
}

func init() { proto.RegisterFile("akash/inventory/v1/storage.proto", fileDescriptor_98ef685b221b1af7) }

var fileDescriptor_98ef685b221b1af7 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x3f, 0x6f, 0xd3, 0x40,
	0x14, 0x8f, 0x4d, 0x1a, 0xd2, 0x33, 0x11, 0x92, 0xd5, 0x21, 0x74, 0xf0, 0x8b, 0x4e, 0x8a, 0xc4,
	0x1f, 0x61, 0xab, 0x61, 0x41, 0x95, 0x58, 0xd2, 0x01, 0x45, 0xaa, 0x14, 0x30, 0x88, 0x81, 0xed,
	0x6a, 0x1c, 0xf7, 0xd4, 0xd4, 0x17, 0xce, 0x4e, 0x50, 0x3e, 0x01, 0x2b, 0x1f, 0x8b, 0xb1, 0x03,
	0x03, 0xd3, 0x13, 0xba, 0x6c, 0x1e, 0x3d, 0x32, 0x21, 0xdf, 0x5d, 0x02, 0x11, 0x95, 0xba, 0xdd,
	0xfd, 0xfe, 0xbc, 0x7b, 0xbf, 0xf7, 0x8e, 0x0c, 0xd8, 0x15, 0x2b, 0x2e, 0x23, 0x9e, 0xaf, 0xd2,
	0xbc, 0x14, 0x72, 0x1d, 0xad, 0x4e, 0xa2, 0xa2, 0x14, 0x92, 0x65, 0x69, 0xb8, 0x90, 0xa2, 0x14,
	0xbe, 0xaf, 0x15, 0xe1, 0x4e, 0x11, 0xae, 0x4e, 0x8e, 0x8f, 0x32, 0x91, 0x09, 0x4d, 0x47, 0xcd,
	0xc9, 0x28, 0x8f, 0x87, 0xb7, 0xd4, 0x92, 0x69, 0x21, 0x96, 0x32, 0x49, 0x17, 0x8c, 0x4b, 0x2b,
	0x7b, 0x7a, 0x87, 0x6c, 0x2e, 0x12, 0x36, 0x37, 0x5a, 0xfa, 0xdb, 0x21, 0xde, 0x3b, 0xd3, 0xce,
	0x24, 0x9f, 0x09, 0xff, 0x15, 0xe9, 0xac, 0xd2, 0xfc, 0x93, 0x90, 0x7d, 0x67, 0xe0, 0x3c, 0x3e,
	0x1c, 0x0f, 0x15, 0x42, 0xe7, 0x83, 0x46, 0x2a, 0x04, 0xcb, 0xd5, 0x08, 0xbd, 0x35, 0xbb, 0x9e,
	0x9f, 0x52, 0x73, 0xa7, 0xb1, 0x25, 0xfc, 0x97, 0xe4, 0x20, 0x99, 0xb3, 0xa2, 0xe8, 0xbb, 0xda,
	0x4d, 0x15, 0xc2, 0xc1, 0x59, 0x03, 0x54, 0x08, 0x86, 0xa9, 0x11, 0x1e, 0x18, 0xaf, 0xbe, 0xd2,
	0xd8, 0xc0, 0xfe, 0x6b, 0xd2, 0x4d, 0xd8, 0x82, 0x25, 0xbc, 0x5c, 0xf7, 0xef, 0x69, 0xf3, 0x33,
	0x85, 0xd0, 0x3d, 0xb3, 0x58, 0x85, 0xb0, 0xe3, 0x6b, 0x84, 0x87, 0xb6, 0x84, 0x45, 0x68, 0xbc,
	0x23, 0xfd, 0x27, 0xc4, 0x9d, 0x4c, 0xfb, 0x6d, 0x5d, 0xe2, 0x91, 0x42, 0x70, 0x27, 0xd3, 0x0a,
	0xc1, 0xe5, 0xa2, 0x46, 0x38, 0x34, 0x36, 0x2e, 0x68, 0xec, 0x4e, 0xa6, 0xf4, 0x87, 0x4b, 0xee,
	0xdb, 0xf0, 0x3e, 0x27, 0xdd, 0xcf, 0x4b, 0x96, 0x97, 0xcd, 0xfb, 0x4d, 0x74, 0x6f, 0x34, 0x08,
	0xff, 0x5f, 0x4c, 0x18, 0xdb, 0x39, 0xbe, 0x61, 0x5c, 0x9a, 0x0e, 0xdf, 0x5a, 0x57, 0xd3, 0xe1,
	0xb6, 0xc2, 0xdf, 0x0e, 0xb7, 0x08, 0x8d, 0x77, 0xa4, 0xff, 0x9e, 0xb4, 0x79, 0x3e, 0x13, 0x7a,
	0x46, 0xde, 0x08, 0x6e, 0x7b, 0xe6, 0x9f, 0x95, 0x8c, 0x41, 0x21, 0xb4, 0x9b, 0x53, 0x85, 0xa0,
	0x8d, 0x35, 0x82, 0x67, 0x83, 0xe4, 0x33, 0x41, 0x63, 0x0d, 0xfa, 0x5f, 0x1d, 0xd2, 0xdb, 0x3e,
	0xa1, 0x37, 0xac, 0xc7, 0xe8, 0x8d, 0x86, 0x77, 0xc5, 0x38, 0x6f, 0xc4, 0xe3, 0x53, 0x85, 0xd0,
	0xdb, 0x66, 0xd1, 0x50, 0x85, 0xb0, 0x5f, 0xb0, 0x46, 0x38, 0xda, 0x4f, 0xa5, 0x61, 0x1a, 0xef,
	0xcb, 0xc6, 0xe7, 0xdf, 0x55, 0xe0, 0xdc, 0xa8, 0xc0, 0xf9, 0xa5, 0x02, 0xe7, 0xdb, 0x26, 0x68,
	0xdd, 0x6c, 0x82, 0xd6, 0xcf, 0x4d, 0xd0, 0xfa, 0x38, 0xca, 0x78, 0x79, 0xb9, 0xbc, 0x08, 0x13,
	0x71, 0x1d, 0xe9, 0xae, 0x9e, 0xe7, 0x69, 0xf9, 0x45, 0xc8, 0x2b, 0x7b, 0x63, 0x0b, 0x1e, 0x65,
	0x62, 0xef, 0xe7, 0x5e, 0x74, 0xf4, 0x47, 0x7d, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x09, 0x23,
	0xc2, 0x24, 0x49, 0x03, 0x00, 0x00,
}

func (m *StorageInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StorageInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StorageInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IO) > 0 {
		i -= len(m.IO)
		copy(dAtA[i:], m.IO)
		i = encodeVarintStorage(dAtA, i, uint64(len(m.IO)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Capacity) > 0 {
		i -= len(m.Capacity)
		copy(dAtA[i:], m.Capacity)
		i = encodeVarintStorage(dAtA, i, uint64(len(m.Capacity)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Class) > 0 {
		i -= len(m.Class)
		copy(dAtA[i:], m.Class)
		i = encodeVarintStorage(dAtA, i, uint64(len(m.Class)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Vendor) > 0 {
		i -= len(m.Vendor)
		copy(dAtA[i:], m.Vendor)
		i = encodeVarintStorage(dAtA, i, uint64(len(m.Vendor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Storage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Storage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Storage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.QuantityLocal != nil {
		{
			size, err := m.QuantityLocal.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStorage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Info != nil {
		{
			size, err := m.Info.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStorage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Quantity != nil {
		{
			size, err := m.Quantity.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStorage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStorage(dAtA []byte, offset int, v uint64) int {
	offset -= sovStorage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StorageInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Vendor)
	if l > 0 {
		n += 1 + l + sovStorage(uint64(l))
	}
	l = len(m.Class)
	if l > 0 {
		n += 1 + l + sovStorage(uint64(l))
	}
	l = len(m.Capacity)
	if l > 0 {
		n += 1 + l + sovStorage(uint64(l))
	}
	l = len(m.IO)
	if l > 0 {
		n += 1 + l + sovStorage(uint64(l))
	}
	return n
}

func (m *Storage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Quantity != nil {
		l = m.Quantity.Size()
		n += 1 + l + sovStorage(uint64(l))
	}
	if m.Info != nil {
		l = m.Info.Size()
		n += 1 + l + sovStorage(uint64(l))
	}
	if m.QuantityLocal != nil {
		l = m.QuantityLocal.Size()
		n += 1 + l + sovStorage(uint64(l))
	}
	return n
}

func sovStorage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStorage(x uint64) (n int) {
	return sovStorage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StorageInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStorage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StorageInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StorageInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vendor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vendor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Class", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Class = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capacity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Capacity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IO", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IO = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStorage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStorage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Storage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStorage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Storage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Storage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStorage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Quantity == nil {
				m.Quantity = &ResourcePair{}
			}
			if err := m.Quantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStorage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Info == nil {
				m.Info = &StorageInfo{}
			}
			if err := m.Info.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuantityLocal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStorage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.QuantityLocal == nil {
				m.QuantityLocal = &ResourcePairLocal{}
			}
			if err := m.QuantityLocal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStorage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStorage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStorage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStorage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStorage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStorage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStorage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStorage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStorage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStorage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStorage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStorage = fmt.Errorf("proto: unexpected end of group")
)
